### ISSUE TITLE
Cardano.Crypto.Util.nonNegIntR relies on Int being 64-bit

### ISSUE THREAD

**Issue by Vtec234** [input-output-hk/cardano-base#31]
`Cardano.Crypto.Util.nonNegIntR` ([link](https://github.com/input-output-hk/cardano-base/blob/6b808ad5506cb097cdf5832e1cd5cad0c83c58d6/cardano-crypto-class/src/Cardano/Crypto/Util.hs#L17)) sounds like it should return non-negative integers. However, it relies on the `Int` type being at least 33-bits wide (so that the max value is at least 2^32-1), which in practice would be 64-bit, while the Haskell spec [states](https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Int.html) that `Int` has "at least the range [-2^29 .. 2^29-1]". In practice, if `Int` is `Int32`, half of the time this function will return a negative value. (See input-output-hk/ouroboros-network#770).

**Comment by erikd** [comment]
The haskell spec is pretty much irrelevant because there really is only one Haskell compiler (GHC) that people could use to compile a project like this. Furthermore, on 64 bit archtectures GHC's `Int`is a 64 bit signed integer and we currently only support Linux, Mac and Windows on `x86_64`.

However, in cases where data should be non-negative, `Word` is probably a better choice than `Int`.

**Comment by mark-stopka** [comment]
> The haskell spec is pretty much irrelevant because there really is only one Haskell compiler (GHC) that people could use to compile a project like this. Furthermore, on 64 bit archtectures GHC's `Int`is a 64 bit signed integer and we currently only support Linux, Mac and Windows on `x86_64`.
> 
> However, in cases where data should be non-negative, `Word` is probably a better choice than `Int`.

Hi Eric, how does the whole 

> we currently only support Linux, Mac and Windows on `x86_64`.

tie in with [Cardano on Rocks](https://forum.cardano.org/t/check-this-out-cardano-on-the-rocks/28952) initiative which was highly marketed as a added value of Cardano and PoS in general? It was even mentioned by @CharlesHoskinson several times, including [this one](https://www.youtube.com/watch?v=f-rqaTLwWgs&t=365s) as a marketing pitch.

Current set of issues is not only this particular one, but also requirement for GHC bootstrap as the used version of GHC is not pre-compiled for ARM64 platform.

**Comment by erikd** [comment]
I made that statement on July of 2019. I was not aware of the desire to support ARM64 at that time.

**Comment by mark-stopka** [comment]
Sure, and I hope you're not taking it personally, but I have actually tried to build `cardano-node` as a whole on AArch64 (ARMv8) when writing the README.md guide, so I am asking about it as many people made the investment for the hardware for the ITNv1. I haven't given it much time, but attempt to build on this arch results in:

```
No setup information found for ghc-8.6.5, bindist has not yet been added for OSkey linux-aarch64.
Supported versions ghc-8.2.1 8.2.2 8.4.1 8.4.2 8.6.2 8.8.1 8.8.2
```

Latest version I found for [AARCH64 was 8.6.3](https://www.haskell.org/ghc/download_ghc_8_6_3.html#linux_aarch64) which is actually missing as per [ghc#16060](https://gitlab.haskell.org/ghc/ghc/issues/16060).

Anyhow, any version `haskell stack` has been able to download and install was `ghc-8.4.1` and I have not tried to use that to bootstrap the `cardano-node` required version as defined in `stack.yaml` - `ghc-8.6.5` because I had no free machine time for that yet.

I suppose we should move ARM support as a separate issue into the `cardano-node` repo and take it from there step-by-step? To at least identify if there are actuall issues other than build infrastructure bootstrap? Or would you prefer to continue the conversation here?

**Comment by karknu** [comment]
> Current set of issues is not only this particular one, but also requirement for GHC bootstrap as the used version of GHC is not pre-compiled for ARM64 platform.
I've not tried cardano on rocks, but I own two Rockpi boards which I'm using to test `cardano-node` on.

The requirement to compile a new version of ghc is a linux dist/ghc  issue and not a problem with cardano. Last year Armbian shipped with ghc 8.0.x  which meant that one would have to compile ghc 8.4.2 in order to compile ghc 8.6.x.

At the moment I'm aware of one issue which affects rockpi, and Arm boards in general, https://gitlab.haskell.org/ghc/ghc/merge_requests/734 . That bug requires us to run cardano-node using with a single OS thread (`+RTS -N1`).

**Comment by karknu** [comment]
@mark-stopka 
Forgot one more issue.
There is bug with the HW offloading for TCP checksum calculations on rockspi so it must be disabled.
Command:
/sbin/ethtool --offload eth0 rx off tx off

**Comment by mark-stopka** [comment]
@karknu, it also seems the pull request you linked was fixed by [PR 1128](https://gitlab.haskell.org/ghc/ghc/merge_requests/1128), which should be part of 8.8.1 GHC build.

As per the faulty TCP offload engine it seems nobody ever touched that part of [code in the kernel](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-5.5.y&qt=grep&q=RK3399).

**Comment by mark-stopka** [comment]
> The requirement to compile a new version of ghc is a linux dist/ghc issue and not a problem with cardano.

It's a `haskell stack` issue, I looked into it and recent enough versions of `stack` should support GHC bootstrap, so I try to look into it and kill two flies with one stone, because pre-compiled GHC from hackage also requires `libtinfo.so` and the linker does not recognize `libtinfo.so.6` as a valid candidate. Looks like hackage dist versions of GHC are build on Debian / Ubuntu platform and requires an ugly symlink hack on all other platforms compliant with [LSB](https://en.wikipedia.org/wiki/Linux_Standard_Base).

**Comment by erikd** [comment]
I would recommend `cabal` over `stack`. The majority of the teams working on the new code base prefer `cabal`.

**Comment by lehins** [comment]
`nonNegIntR` function that this ticket is about has been removed. Moreover, it is reasonable to assume that we do not support architectures that are at least 64 bits, so `Int` being represented by something like 32bit Int or smaller is not irrelevant. Minimum amount of RAM required for a node is 24Gb, which is not possible on 32bit machines.
